### ISSUE TITLE
EP: Push Notifications

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#1]
# EPIC

### Acceptance Criteria
- [x] Allows for remote push notifications
- [x] Certificate
- [x] Received push notifications 
- [x] Registered for remote notifications successfully

**Comment by ksigWyatt** [comment]
### Note
Doing research on which platform might be the easiest to add / cost effective. Leaning towards`Firebase`

**Comment by ksigWyatt** [comment]
This will not be part of Release 1.5.1 but will be in 1.6.

Still in this sprint hopefully

**Comment by ksigWyatt** [comment]
Intermittent issues still persist

**Comment by ksigWyatt** [comment]
Added this epic to it's own Pipeline - `Spike!` because there's too much here to figure out what's wrong

**Comment by ksigWyatt** [comment]
Uploading `1.6.1.7` to iTunes Connect for Beta Testing.
