### ISSUE TITLE
Capture if user's network activity is too slow and adjust load / include reload for fail

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#103]
## Tasks
- [x] Add a label on the front CollectionView that will hide the collection view then display over top of it and say "Unable to load data. Please check your internet connection and try again."
- [x] We will need to add a button underneath that so we can retry.

## Stretch Goals
- [ ] If we can see that a download is taking some time we should replace the image that we are downloading for the thumbnail because that file is roughly 10% the size of the full quality `Art` image.

**Comment by ksigWyatt** [comment]
We will need to allow up to 2 minutes for all responses to come back, because unfortunately connections are sometimes slow. We could narrow that to 1 minute and see what images are taking a while? (I don't think we can do that). I think this will be addressed by #108.
