### ISSUE TITLE
Enable paging for CollectionView if a response is large

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#108]
## User Story

As a Developer I want my application to run fast, so that a user can access info quickly without the need to load things they may not see.

### Acceptance Criteria
- [x] API responds with a paged response
- [x] API response is parsed and placed into a data type that can be quickly accessed
- [x] Paging is enabled for the main CollectionViewController
- [x] 5 items are loaded on init, 5 the next time and then every time after the 2nd it pages with 10 at a time 

## Tasks
- [x] Wait for API changes
- [x] Parse API response
- [x] Enable Paging
- [ ] Make it happen 🎉

**Comment by ksigWyatt** [comment]
This issue is blocked until the API route can be updated for this

**Comment by ksigWyatt** [comment]
API is done and merged in, Will continue work on this.

**Comment by ksigWyatt** [comment]
Bug solution for the bug we have rn

Add footer view for collection view and add contentoffset in bottom for lazy loading in collection view

**Comment by ksigWyatt** [comment]
^ Verified that the above solution is present and works. Might have to tweak the values slightly, but she's purring.
