### ISSUE TITLE
Enable reading of bible passages from Sermon View

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#114]
## User Story

As a user I want to be able to easily read the bible passages within a sermon series, so that I can reference the passage that the speaker is speaking on.

### Acceptance Criteria
- [x] A new view opens to show the passage text
- [x] The title on the top of the Navigation Controller is the title of the text being shown (Psalms 119)
- [x] Text is shown already preformatted from the API and should appear with verse numbers as superscript unicode characters.

## Tasks
- [x] Add the new View
- [x] Add a `didSet` for the header to be set before page load based on the message's `PassageRef`
- [x] Connect it to our API and render the message in the response
- [x] Include a spinner for long loading API messages

**Comment by ksigWyatt** [comment]
See more https://stackoverflow.com/questions/31272561/working-with-unicode-code-points-in-swift

**Comment by ksigWyatt** [comment]
Currently blocked by the API

**Comment by ksigWyatt** [comment]
Unblocked
