### ISSUE TITLE
Minor Bug Fixes & Improvements

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#116]
### Task

**TODOs:**
- [x] When a sermon message is downloaded, and a user attempts to play the audio from the SermonSeriesView, we need to make sure that we play the downloaded version on the device and NOT stream a new version again using more data.
- [x] There are some weird bugs when a user is on the currently playing view, and when they return to the CollectionView, they cannot tap on a cell in the collection view. This should be fixed.
    - I think that this is something as simple as calling `reload()` on the collection view whenever we return to the collection view. It MAY - not sure - be that the system is collecting this memory because we are dismissing the view. So the event handlers on the cells are not listening. However when we call reload, by scrolling down farther or loading more cells through paging then the handlers work again.
- [x] More testing is needed to ensure that performance is adequate. 
- [ ] ~~Fix the audio file duration / current time progress bar to reflect the current time + and the duration. The duration needs to include an extra 0 at the beginning if the seconds value is < 10.~~
- [x] Fix an issue where the recently played list will contain the same message more than once. We add it to the 0th index to preserve stack ordering (but we need to check if it's in there first and remove it from where it is before adding it to the 0th index)

**Comment by ksigWyatt** [comment]
Need to make sure that I also update the start date of Galatians. It currently says the 3rd but it should be the 10th of the month

**Comment by ksigWyatt** [comment]
I also need to make sure that the pause button is disabled if the playback reaches the end. At which point the user can tap pause again to set the playback time to 0 and the message will restart. I’ll need to make sure I update the progress bar there too.

**Comment by ksigWyatt** [comment]
So after some investigation into what the system is doing to the collection view, I have determined (not officially) that the OS is de-allocating some of the memory and collecting some of it because the collection view is now in the background as part of the app.

However, what this means is that there's no Event Driven methods that we could use to simply call `reload()` on and trigger this usability again. SO...

What does this mean?

I'll need to be a bit more clever on how we're going to solve this issue... Will report back when I am able to determine what to do here.

**Comment by ksigWyatt** [comment]
Vote to remove the playback bar entirely? Its too annoying to manage... and apparently `NaN` is a valid state for this to hold.

**Comment by ksigWyatt** [comment]
Initial testing indicates that the UI performance is adequate, in most cases 3x faster than the previous design in terms of viewing messages within a particular sermon series.

**Comment by ksigWyatt** [comment]
Will be removing the playback progress bar... that can come in `v1.7.1`

**Comment by ksigWyatt** [comment]
Was able to fix the issue in bullet 2.
