### ISSUE TITLE
Show Activity indicator when download on the Player View is currently downloading

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#118]
## User Story

As a User I want to see that my download is actually happening, so that I don't need to tap the icon multiple times and so that I know what is happening on my device.

### Acceptance Criteria
- [x] spins while download is active
- [x] stops and shows grayed out download button if message download was successful

## Tasks
- [x] DO IT

## Stretch Goals
- [ ] Make it a round icon that shows the actual download progress

**Comment by ksigWyatt** [comment]
Worked as part of #116
