### ISSUE TITLE
Implement AudioDuration for Sermon Messages

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#120]
## User Story

As a developer I want the duration of the audio files BEFORE I download them on a slow connection, so that I can display to the user their current progress along the audio file.

### Acceptance Criteria
- [x] Add properties to the Model
- [x] Add the property to the codable protocol stubs
- [x] Look for the duration within the now playing tab -- THE RIGHT WAY

## Stretch Goals
- [x] display the duration on the sermon series page, so that the user knows how long a sermon will be

## Tasks
- [x] DO IT!
