### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#128]
## User Story

As a Developer I want to see all error logs , so that I can fix them in a timely manner.

### Acceptance Criteria
- [ ] API or local logging on device for errors

## Tasks
- [ ] Figure something out
- [ ] Would be nice it we could make this configurable
