### ISSUE TITLE
Scroll Views Not Displaying Properly & Misc.

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#13]
## Task 1

- [x] Fix all the Scroll view issues on View Controllers
    - [x] Give
    - [x] About
    - [x] Check for others

**Note** - _Some are passing:_
1. `ThriveFGCU`
2. `Contact`

## Task 2

- [x] Fix `SocialVC` 
    _The constraints for `Web` are broken or break during VC load_
- [x] Fix Launch Screen for iPhone 4s

## ~~Task 3~~ *Abandoned because of blockers (Issue #19)*
- [ ] Change `Contact VC` to become a `Modally` presented VC - _Fix bugs before approval_
    - [x] Change Transition Style to `Cross-Dissolve`
    - [x] Change Presentation Style to `Over Current Context`
    - [x] Make it look "Pretty" ;)
- [x] Fix breaking constraints
   _Secondary Breaking Contraints are due to `3.5 inch` screen format._
- [x] Fix Secondary Breaking Contraints... Somehow

**Blockers**
1. `MFMailComposeViewController` will not dismiss itself when using a `Modal VC`. Even when explicitly calling:
```
self.dismiss(animated: true, completion: nil)
// OR
dismiss(animated: true, completion: nil)
``` 

### Bugs
1. When the `popUpVC` is closed the `UITableViewCell` _Contact Us_ is still selected and grey.
2. Blockers above

**Comment by ksigWyatt** [comment]
Testing Complete - Minor bugs still persist. Will be fixed in next PR
