### ISSUE TITLE
Playing Videos Locally

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#133]
## User Story

As a User I want to be able to play the sermon videos locally, so that I don't need to have multiple apps installed and so that I can stay within the application.

### Acceptance Criteria
- [x] The sermon videos are played within the application using the corresponding API
- [ ] If a user closes the screen or moves the video to the background the audio should continue to play.
- [x] The setting should be set within the settings screen of the Application itself, and defaults to playing locally. The user should be able to enable the use of the YouTube application however.

## Tasks
- [ ] Make it happen!

**Comment by ksigWyatt** [comment]
Unable to meet AC 2, this seems to be an issue with iOS itself. See https://forums.developer.apple.com/thread/121822
