### ISSUE TITLE
Making Values Configurable

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#144]
## User Story

As a Church leader I want to change values to certain items without updating the application, so that I can save time in a number of areas.

### Acceptance Criteria
- [x] Things like contact information (phone numbers emails need to be configurable)
- [x] URL links to website related information needs to be configurable
- [x] Livestream links need to be configurable

## Tasks
- [x] Remove the "hard-coding" aspect of the application

**Comment by ksigWyatt** [comment]
Note: Values are re-saved to the device every time the application loads
