### ISSUE TITLE
Configure ESV API

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#16]
## User Story
As a user, I want to be able to read the entire bible, so that I can read the word and follow along on Sunday morning

### Acceptance Criteria
- [x] ESV API Key Accepted
- [x] Using Valid API Query Strings
- [x] API returns are used to display Chapters / Books / Verses etc.

## Tasks
- [x] Configure API
- [x] Access the API
- [ ] Parse API return from endpoint
- [x] Design a UI to display the return
_There might need to be some research done to see which way might be the most efficient way to display everything._

**Comment by ksigWyatt** [comment]
It's a web-server API 🙄. Time to config the website for it

**Comment by ksigWyatt** [comment]
Got it! Time to add JSON Serialization.

**Comment by ksigWyatt** [comment]
**Special thanks to ESV API v3** making it easier to return JSON than v2. 

Serialize 
`"passages": [ ]` - An array of "verses". Not sure why it's an array since there's 1 value, a huge string but either way it works.

RESPONSE:
<img width="917" alt="screen shot 2017-10-23 at 12 19 55 pm" src="https://user-images.githubusercontent.com/22202975/31900522-a6c99cec-b7ec-11e7-95b2-256fde40bb0c.png">

**Comment by ksigWyatt** [comment]
Connected to ESV endpoint. But must configure the access. I keep getting `403` even though I know the connection is made. But maybe I'm wrong

**Comment by ksigWyatt** [comment]
Deemed out of scope at this time for the project.
