### ISSUE TITLE
Watch / Listen progression 

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#170]
## User Story
As a user I want the application to remember how much of a certain video / audio file I've listened to, so that I can resume from there.

### Acceptance Criteria
- [ ] Playback progress should be tracked for this user so that they can resume play at the same or within ~10s or so of where they left off
- [ ] Users are required to sign-in in order to use this feature
- [ ] If users have a partially played file, they will have the option to resume playing from where they last were.

## Tasks
- [ ] The API should be the one that stores this information
- [ ] We'll need to track the user's ID and the media item ID, and type (Audio/Video) so that we know where the user should start from. 
- [ ] If the user completed the playback or is within ~10s we'll remove this and mark that the user has listened to this whole file.
- [ ] The API will need to be able to process many of these requests quickly, most of which are an increment / removal operations for when users are listening / have completed listening to a file.
