### ISSUE TITLE
Modal View Controllers

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#19]
## Task
- [ ] Change `Contact VC` to become a `Modally` presented VC - _Fix bugs before approval_
    - [x] Change Transition Style to `Cross-Dissolve`
    - [x] Change Presentation Style to `Over Current Context`
    - [x] Make it look "Pretty" ;)
- [x] Fix breaking constraints
   _Secondary Breaking Contraints are due to `3.5 inch` screen format._
- [x] Fix Secondary Breaking Contraints... Somehow

## **Blocker**
`MFMailComposeViewController` will not dismiss itself when using a `Modal VC`. Even when explicitly calling:
```
self.dismiss(animated: true, completion: nil)
// OR
dismiss(animated: true, completion: nil)
``` 

### Bugs
1. When the `popUpVC` is closed the `UITableViewCell` _Contact Us_ is still selected and grey.

**Comment by ksigWyatt** [comment]
Removing **_Crash_** Label because technichally the application doesn't crash, it becomes inoperable following the dismissal of a `NSMailViewController`

**Comment by ksigWyatt** [comment]
Note to self -- Create a new Issue for the Blocker and create an **EPIC** for this issue by itself since the estimate is so high. Likely due to the time it may take to fix the issues with the bugfix

**Comment by ksigWyatt** [comment]
Convert this to only a `Spike!` because I want to think about if whether or not I want to even use a "Modally" presented view controller.

**Comment by ksigWyatt** [comment]
**Closing this issue** because after thinking about it - it would be nice but the work required to get it working is quite annoying so. I'll revisit this issue when that time comes

**Comment by ksigWyatt** [comment]
I may reopen this issue - will advise later
