### ISSUE TITLE
Firebase Analytics

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#30]
## User Story
As a Software Developer, I want to know where my users are engaging the application so that I can make the features utilized better, or remove ones that aren't used very often.

### Tasks
- [x] Init of Firebase

## Acceptance Criteria
- [x] The application is registered with Firebase on launch
- [x] Actions are registered with the Firebase Server in real-time

## Stretch Goals
- [ ] Add custom events for special segues
