### ISSUE TITLE
FCM Address not printing for physical devices

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#40]
# Blocker

- FCM Address must be printed for the devices to be tested properly. Perhaps there's an issue with iOS 11?

## Tasks
 - [ ] Submit a support token to Google - _If you can... not sure?_
 - [ ] Test that there's not something that I need to add to the code in the registration. The docs suggest that in iOS 10 there's extra that needs to be done. 
_See Screenshot_
<img width="851" alt="screen shot 2017-09-21 at 9 45 13 pm" src="https://user-images.githubusercontent.com/22202975/30725963-340e5db2-9f16-11e7-9129-0a632f547a52.png">

 - [x] Test that the FCM token prints properly

**Comment by ksigWyatt** [comment]
**FCM** Address prints but it does it when it feels like it

**Comment by ksigWyatt** [comment]
My Certificate expired 😠 . Need to download a new one here soon. That might be why everything is all messy. I might just redo every certificate all at once then - just so it's easier

**Comment by ksigWyatt** [comment]
This is so annoying...
<img width="1034" alt="screen shot 2017-10-23 at 9 50 14 am" src="https://user-images.githubusercontent.com/22202975/31892868-0dc88486-b7d8-11e7-88cd-0f72570d57ba.png">

**Comment by ksigWyatt** [comment]
Works on 2nd startup.... so annoying

**Comment by ksigWyatt** [comment]
Got it working another way
