### ISSUE TITLE
SG: Use firebase Database for Notes that have been taken

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#41]
## Stretch Goal
As a user, I want my notes to be saved, even if I delete the app. So that I can keep them on my device and not have to worry about ever loosing them

### Acceptance Criteria
- [x] Notes are saved in Firebase Database / Storage Servers
- [x] Notes are able to be retrieved from the database
- [ ] Deleted notes are removed from both the database as well
- [x] Once the app and all data have been removed - the notes still populate the table. 

## Tasks
- [x] Config the Firebase database
- [x] Add the database to the application
- [ ] **TESTING**
- [ ] Delete the app and try to see if you can recover the notes you took. 
_This might get tricky because I'll have to store it in the database and if they match then populate the `TableView` with the notes that have been synced._
- [ ] Pull-Down to refresh

**Comment by ksigWyatt** [comment]
Is this worth adding as a feature?

Need to think about if this is a worthy addition to the App, because I'm not 100% that I want to continue after talking to some users after a short testing session

**Comment by ksigWyatt** [comment]
Remove feature from `1.7`
This can be added in a future update - maybe 2.0
