### ISSUE TITLE
Save note to Firebase

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#55]
## User Story

As a User I want my notes to be saved to the cloud, so that they aren't deleted if I delete the app.

### Acceptance Criteria
- [x] Notes are saved in Firebase DB
- [ ] Notes that are deleted are deleted from the DB as well
- [x] Each note is given a UUID so that if a user has hundreds of notes then there will be no issue 

## Tasks
- [x] Config Firebase
- [x] Add fake note to DB
- [ ] Test UI to ensure that changes persist
- [ ] Design new UI elements to notify users that notes have been saved or are not saved

**Comment by ksigWyatt** [comment]
`label` attribute is a little redundant -- since the Label on the TableView cuts the label to the beginning several characters of the note. So we only really NEED to store the note as an attribute, as this can be used to create the label in the future. Otherwise it messes things up. Because that's how it works now. The text in the note is assigned to the label of the selected row index. That seems like the best way to do it.

**Comment by ksigWyatt** [comment]
Creating new issue solely for checking if a note exists or not - it seems to be a large enough issue

**Comment by ksigWyatt** [comment]
Out of scope - might reopen this issue if the need arises
