### ISSUE TITLE
Check if note exists in Firebase before saving

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#58]
## User Story

As a developer I want to make sure that I don't save the same note twice , so that I don't have many duplicate notes in the database.

### Acceptance Criteria
- [x] Duplicate notes are identified
- [ ] Notes that have the same ID / Text are not allowed to be saved

## Tasks
- [x] Get logic working
- [ ] Test it

Easy enough...

**Comment by ksigWyatt** [comment]
Logic works but I'm trying to configure a Bool function that returns true if a note exists because I'll be calling it often. That just makes sense. So I'm making the estimate a little higher because of that.

**Comment by ksigWyatt** [comment]
also there's a couple other issues associated with the login action -- testing revealed that sometimes the login action isn't fully completed... that can be frustrating for some users. I think however that it's an issue of connectivity. Or a firebase issue.
