### ISSUE TITLE
Configure for iOS 11

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#6]
## User Story
As a user, I want the application to operate as expected on any of my devices.

### Acceptance Criteria
- [x] Application runs successfully on iOS 11, without crashing

## Tasks
- [x] Massive UI Changes

- [ ] ~~Configure ESV API to work properly~~
_Not an iOS 11 related task_

**Comment by ksigWyatt** [comment]
## Testing Results
**Physical Device Testing** - Passed on a number of tests & UI is scaling as expected.

### Note
Several features still need to be fixed in this sprint. These are already added as separate issues on their own. _This US however, is passing. Excluding those minor issues, on iOS 11._
