### ISSUE TITLE
Attach Log files to emails

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#68]
## User Story

As a developer I want device info sent to me with a feedback email , so that I can better implement the feature for that device or understand the problem at hand.

### Acceptance Criteria
- [x] Log Files are added as attachments to the email
- [x] Personal data is not part of the file and only that data that the user enters in the field of the email will be used in response to the emal

## Tasks
- [ ] Might need to use a library for this one
- [ ] look into it

**Comment by ksigWyatt** [comment]
Using `FileManager` might work in Swift 4. Just need to convert this example.
```
let dir:NSURL = NSFileManager.defaultManager().URLsForDirectory(NSSearchPathDirectory.CachesDirectory, inDomains: NSSearchPathDomainMask.UserDomainMask).last as NSURL
let fileurl =  dir.URLByAppendingPathComponent("log.txt")

let string = "\(NSDate())\n"
let data = string.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!

if NSFileManager.defaultManager().fileExistsAtPath(fileurl.path!) {
    var err:NSError?
    if let fileHandle = NSFileHandle(forWritingToURL: fileurl, error: &err) {
        fileHandle.seekToEndOfFile()
        fileHandle.writeData(data)
        fileHandle.closeFile()
    }
    else {
        println("Can't open fileHandle \(err)")
    }
}
else {
    var err:NSError?
    if !data.writeToURL(fileurl, options: .DataWritingAtomic, error: &err) {
        println("Can't write \(err)")
    }
}
```
