### ISSUE TITLE
Note with "New Note" only as text is Overritten by creating a new note

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#70]
## User Story

As a dev I want things to not be deleted on accident , so that the user's information is stored as expected.

### Acceptance Criteria
- [x] Text inside a note as `New Note` will not be deleted if in the table view, a user taps Add new note

## Tasks
- [x] fix logic for creating a new note
- [x] add check for if the text == something then do something else
