### ISSUE TITLE
Onboarding 

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#83]
## User Story

As a user I want to know what features are inside the application and how to use them , so that I can use the application to its potential.

### Acceptance Criteria
- [x] Shows all the features of the application in a neat way

## Tasks
- [x] Use the existing Onboarding example I have to build it in. 
- [x] Store completed inside `UserDefaults`
