### ISSUE TITLE
Further WebView Optimizations & OOP minded Design

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#85]
## Tasks
- [x] Convert the WebViews to something that uses a master delegate for loading the web pages
- [x] Add loading spinners to central "master" delegate 
- [x] Pass link with spinner to load and present a new view and be able to dismiss it with back button in navigation controller

### Stretch Goals
- [x] with a title to the new controller

**Comment by ksigWyatt** [comment]
Dev complete begin QA

**Comment by ksigWyatt** [comment]
Passed QA

**Comment by ksigWyatt** [comment]
`13.4 MB` on iPhone to now `43.6 MB` I'll need to look into why now the application has gotten almost 4x larger
