### ISSUE TITLE
Global Application Settings

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#96]
## User Story

As a user I want to be able to update settings for the entire application, so that everything looks / works as I want it to.

### Acceptance Criteria
- [ ] Add global setting for application color; light / dark
- [x] Global setting for ThriveChurchOfficialAPI locale

## Tasks
- [x] See https://medium.com/@abhimuralidharan/adding-settings-to-your-ios-app-cecef8c5497
- [x] Do it
- [x] See also https://stackoverflow.com/a/41391425/6448167
