### ISSUE TITLE
Viewing Live-streams

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#97]
## User Story

As a user I want to be able to view the live-stream from within the app, so that I can still watch from on-the-go or from home without using my computer.

### Acceptance Criteria
- [x] ~~Application can view a live-stream in native video mode~~
*This cannot happen on iOS from Facebook, they do not allow anyone but them to stream video. We will have to open the FB app to that video instead. Or safari if FB isn't installed.*

### Stretch Goals
- [x] ~~Allow the user to be able to close the device and have the audio still playing from the video. Or have the application in the background.~~
*See above*

## Tasks
- [x] Make it happen 🏆!

**Comment by ksigWyatt** [comment]
I might have to rethink this one or just have it open to our Facebook Page.
