### ISSUE TITLE
Offline Listening

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#98]
## User Story

As a user I want to be able to watch the pre-recorded sermons offline, so that I don't have to use my cellular data / wifi network.

### Acceptance Criteria
- [x] ~~Videos can be downloaded to device for viewing offline~~
    _Decided not to do offline videos, this would take a lot of space up on a user's device and YT already supports downloading videos with YT red._
- [x] Audio can be downloaded to device for listening offline
- [x] Downloads library will need to be a Tab on the UI

## Tasks
- [x] Make it happen 🎉
