### ISSUE TITLE
Recently Watched / Listened

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#99]
## User Story

As a user I want to know what video / audio I was currently listening to, so that the app can remember things.

### Acceptance Criteria
- [ ] ~~Make it remember where the video / audio was when the user last closed the application~~
*This ended up being a big effort, so instead we just show you what you recently listened to.*
- [x] Handle closing the application because this is annoying with the EDMs
- [x] Create a now playing screen so that users can see what they are currently playing in the background of the device / they can see if they visit that page

## Tasks
- [x] (justdoit)
- [x] Update the cache for this every time a user watches a video, if they watch the entire video - remove it from the cache. OR maybe dont... Will need to flesh out some AC here
